// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89RlzMjcuDmAXhl7yS4u2C4MgG31pDQA',
    appId: '1:342298882584:web:2f1ff16fc730c4837b096d',
    messagingSenderId: '342298882584',
    projectId: 'aluventure',
    authDomain: 'aluventure.firebaseapp.com',
    storageBucket: 'aluventure.firebasestorage.app',
    measurementId: 'G-BN0E5EYLLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAPerjzg6Ci0kLNFteANYeV7VKxavft4',
    appId: '1:342298882584:android:b2b49e815b8441157b096d',
    messagingSenderId: '342298882584',
    projectId: 'aluventure',
    storageBucket: 'aluventure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71bugT2JBCaUh59MBvbDk1vwV2E-e7uA',
    appId: '1:342298882584:ios:2b79030b7dd5538a7b096d',
    messagingSenderId: '342298882584',
    projectId: 'aluventure',
    storageBucket: 'aluventure.firebasestorage.app',
    iosBundleId: 'com.alu.aluventures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71bugT2JBCaUh59MBvbDk1vwV2E-e7uA',
    appId: '1:342298882584:ios:2b79030b7dd5538a7b096d',
    messagingSenderId: '342298882584',
    projectId: 'aluventure',
    storageBucket: 'aluventure.firebasestorage.app',
    iosBundleId: 'com.alu.aluventures',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB89RlzMjcuDmAXhl7yS4u2C4MgG31pDQA',
    appId: '1:342298882584:web:95235e935af9f9bf7b096d',
    messagingSenderId: '342298882584',
    projectId: 'aluventure',
    authDomain: 'aluventure.firebaseapp.com',
    storageBucket: 'aluventure.firebasestorage.app',
    measurementId: 'G-NHHBN1GF1B',
  );
}
